FROM python:3.14-slim

WORKDIR /app

COPY services/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/api/app ./app
COPY frontend ./frontend


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]